-- ────────────────────────────────────────────────────────────────────────────
-- Seed: the 5 launch titles used by the hero + Top 5 Kenya rows.
-- Edit the hls_master_url + thumbnail_url after uploading each transcode to R2.
-- Replace <R2_PUBLIC_HOST> with your R2 custom domain (e.g. assets.birgenai.com).
-- ────────────────────────────────────────────────────────────────────────────

insert into public.kenyan_movies
  (slug, title, description, genres, mood_tags, year, duration_minutes,
   poster_url, thumbnail_url, backdrop_url, trailer_url, hls_master_url,
   tmdb_genre_ids, birgen_rating, language, maturity, is_published, sort_weight)
values
  ('get-out',
   'Get Out',
   'A young African-American visits his white girlfriend''s parents for the weekend, where his simmering uneasiness reaches a boiling point.',
   '{"Horror","Thriller","Mystery"}',
   '{"dark","suspenseful","social-commentary","psychological"}',
   2017, 104,
   'https://<R2_PUBLIC_HOST>/Images/getout.png',
   'https://<R2_PUBLIC_HOST>/Images/getout.png',
   'https://<R2_PUBLIC_HOST>/Images/getout.png',
   'https://<R2_PUBLIC_HOST>/Videos/trailer-getout-2017.mp4',
   'https://<R2_PUBLIC_HOST>/Videos/get-out/master.m3u8',
   '{27,53,9648}',
   4.6, 'en', 'R', true, 100),

  ('sicario',
   'Sicario',
   'An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the U.S.–Mexico border.',
   '{"Crime","Drama","Thriller","Action"}',
   '{"tense","morally-gray","procedural","gritty"}',
   2015, 121,
   'https://<R2_PUBLIC_HOST>/Images/hero-sicario.jpg',
   'https://<R2_PUBLIC_HOST>/Images/hero-sicario.jpg',
   'https://<R2_PUBLIC_HOST>/Images/hero-sicario.jpg',
   'https://<R2_PUBLIC_HOST>/Videos/trailer-sicario-2015.mp4',
   'https://<R2_PUBLIC_HOST>/Videos/sicario/master.m3u8',
   '{28,18,53,80}',
   4.5, 'en', 'R', true, 95),

  ('inception',
   'Inception',
   'A thief who steals corporate secrets through dream-sharing is given the inverse task of planting an idea into a CEO''s mind.',
   '{"Sci-Fi","Action","Thriller","Drama"}',
   '{"mind-bending","cerebral","visual","epic"}',
   2010, 148,
   'https://<R2_PUBLIC_HOST>/Images/hero-inception.webp',
   'https://<R2_PUBLIC_HOST>/Images/hero-inception.webp',
   'https://<R2_PUBLIC_HOST>/Images/hero-inception.webp',
   'https://<R2_PUBLIC_HOST>/Videos/trailer-inception-2010.mp4',
   'https://<R2_PUBLIC_HOST>/Videos/inception/master.m3u8',
   '{28,878,53,18}',
   4.8, 'en', 'PG-13', true, 90),

  ('the-dark-knight',
   'The Dark Knight',
   'When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
   '{"Action","Crime","Drama","Thriller"}',
   '{"dark","gritty","iconic","moral-dilemma"}',
   2008, 152,
   'https://<R2_PUBLIC_HOST>/Images/hero-the-dark-knight-2008.webp',
   'https://<R2_PUBLIC_HOST>/Images/hero-the-dark-knight-2008.webp',
   'https://<R2_PUBLIC_HOST>/Images/hero-the-dark-knight-2008.webp',
   'https://<R2_PUBLIC_HOST>/Videos/trailer-thedarkknight-2008.mp4',
   'https://<R2_PUBLIC_HOST>/Videos/the-dark-knight/master.m3u8',
   '{28,80,18}',
   4.9, 'en', 'PG-13', true, 85),

  ('shutter-island',
   'Shutter Island',
   'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane on a remote island.',
   '{"Mystery","Thriller","Drama"}',
   '{"unsettling","twisty","atmospheric","psychological"}',
   2010, 138,
   'https://<R2_PUBLIC_HOST>/Images/hero-shutter-island.jpg',
   'https://<R2_PUBLIC_HOST>/Images/hero-shutter-island.jpg',
   'https://<R2_PUBLIC_HOST>/Images/hero-shutter-island.jpg',
   'https://<R2_PUBLIC_HOST>/Videos/trailer-shutter-island.mp4',
   'https://<R2_PUBLIC_HOST>/Videos/shutter-island/master.m3u8',
   '{9648,53,18}',
   4.5, 'en', 'R', true, 80)
on conflict (slug) do update set
  title           = excluded.title,
  description     = excluded.description,
  genres          = excluded.genres,
  mood_tags       = excluded.mood_tags,
  year            = excluded.year,
  duration_minutes = excluded.duration_minutes,
  backdrop_url    = excluded.backdrop_url,
  trailer_url     = excluded.trailer_url,
  hls_master_url  = excluded.hls_master_url,
  birgen_rating   = excluded.birgen_rating,
  sort_weight     = excluded.sort_weight,
  updated_at      = now();
