/**
 * BirgenAI content catalogue — single source of truth for investor browse/home rows.
 * R2 layout: Images/{heroes,backdrops,posters,thumbnails,logos,trailers}/ and Videos/...
 * Override NEXT_PUBLIC_R2_PUBLIC_URL so assetUrl() resolves to your bucket.
 */

import { assetUrl } from '@/lib/assets';
import type { Movie } from '@/types';

export interface CatalogEntry {
  movieId: number;
  /** Watch route + HLS folder slug (see lib/hls KENYAN_HLS_MAP for playable titles). */
  slug: string;
  /** Kebab-case id for filenames: poster-{assetKey}.jpg, logo-{assetKey}.png, etc. */
  assetKey: string;
  displayTitle: string;
  year: number;
  runtimeMinutes: number;
  maturity: string;
  tmdbVoteAverage: number;
  overview: string;
  genres: string[];
  playable: boolean;
  comingSoon: boolean;
  kenyanOriginal: boolean;
  panAfrican: boolean;
  darkPsychological: boolean;
  cast: string[];
  director: string;
  filmmakerProfileSlug?: string;
  /** Hero carousel line */
  tagline?: string;
  /** ISO date — "New on BirgenAI" ordering */
  createdAt: string;
  browseSection: string;
  /** Launch titles: point at current public/ assets until R2 is populated. */
  media?: {
    poster?: string;
    backdrop?: string;
    hero?: string;
    logo?: string;
    trailer?: string;
    heroClip?: string;
    preview?: string;
  };
}

/** Default R2-relative paths (wrapped with assetUrl). */
export function catalogPosterPath(e: CatalogEntry): string {
  return e.media?.poster ?? assetUrl(`/Images/posters/poster-${e.assetKey}.jpg`);
}

export function catalogBackdropPath(e: CatalogEntry): string {
  return e.media?.backdrop ?? assetUrl(`/Images/backdrops/backdrop-${e.assetKey}.jpg`);
}

export function catalogHeroPath(e: CatalogEntry): string {
  return e.media?.hero ?? assetUrl(`/Images/heroes/hero-${e.assetKey}.jpg`);
}

export function catalogThumbPath(e: CatalogEntry): string {
  return assetUrl(`/Images/thumbnails/thumb-${e.assetKey}.jpg`);
}

export function catalogLogoPath(e: CatalogEntry): string {
  return e.media?.logo ?? e.media?.poster ?? assetUrl(`/Images/logos/logo-${e.assetKey}.png`);
}

export function catalogTrailerPath(e: CatalogEntry): string {
  return e.media?.trailer ?? assetUrl(`/Videos/trailers/trailer-${e.assetKey}.mp4`);
}

export function catalogHeroClipPath(e: CatalogEntry): string {
  return e.media?.heroClip ?? assetUrl(`/Videos/clips/hero-${e.assetKey}.mp4`);
}

export function catalogPreviewPath(e: CatalogEntry): string {
  return e.media?.preview ?? assetUrl(`/Videos/previews/preview-${e.assetKey}.mp4`);
}

export function isCriticallyAcclaimed(e: CatalogEntry): boolean {
  return e.tmdbVoteAverage >= 8.0;
}

export function toMovie(e: CatalogEntry): Movie {
  const g = e.genres.join('|');
  return {
    movieId: e.movieId,
    title: `${e.displayTitle} (${e.year})`,
    genres: g,
    avg_rating: e.tmdbVoteAverage,
    poster_url: catalogPosterPath(e),
    backdrop_url: catalogBackdropPath(e),
    // Only the playable launch titles have trailer assets in R2.
    trailer_url: e.playable ? catalogTrailerPath(e) : null,
    year: String(e.year),
    overview: e.overview,
    slug: e.slug,
    playable: e.playable,
    comingSoon: e.comingSoon,
    runtimeMinutes: e.runtimeMinutes,
    maturity: e.maturity,
  };
}

export function getCatalogEntryBySlug(slug: string): CatalogEntry | undefined {
  return CATALOG.find((c) => c.slug === slug);
}

export function getCatalogPosterUrlForSlug(slug: string): string | null {
  const e = getCatalogEntryBySlug(slug);
  return e ? catalogPosterPath(e) : null;
}

export function similarCatalogEntries(entry: CatalogEntry, n = 6): CatalogEntry[] {
  const set = new Set(entry.genres);
  const scored = CATALOG.filter((c) => c.slug !== entry.slug).map((c) => ({
    c,
    score: c.genres.filter((g) => set.has(g)).length,
  }));
  scored.sort((a, b) => b.score - a.score || b.c.tmdbVoteAverage - a.c.tmdbVoteAverage);
  return scored.slice(0, n).map((s) => s.c);
}

const sec = (browseSection: string, o: Omit<CatalogEntry, 'browseSection'>): CatalogEntry => ({
  browseSection,
  ...o,
});

/** 38 curated titles — 5 playable HD, rest coming soon / brand story. */
export const CATALOG: CatalogEntry[] = [
  sec('Playable now', {
    movieId: 168250,
    slug: 'get-out',
    assetKey: 'get-out-2017',
    displayTitle: 'Get Out',
    year: 2017,
    runtimeMinutes: 104,
    maturity: 'R',
    tmdbVoteAverage: 7.8,
    overview:
      "A young African-American visits his white girlfriend's parents for the weekend, where simmering unease escalates into terror.",
    genres: ['Horror', 'Thriller', 'Mystery'],
    playable: true,
    comingSoon: false,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Daniel Kaluuya', 'Allison Williams', 'Catherine Keener'],
    director: 'Jordan Peele',
    tagline: '#1 psychological thriller pick',
    createdAt: '2026-01-02T12:00:00.000Z',
  }),
  sec('Playable now', {
    movieId: 139644,
    slug: 'sicario',
    assetKey: 'sicario-2015',
    displayTitle: 'Sicario',
    year: 2015,
    runtimeMinutes: 121,
    maturity: 'R',
    tmdbVoteAverage: 7.7,
    overview:
      'An FBI agent joins a shadowy task force in the brutal border war on drugs between the U.S. and Mexico.',
    genres: ['Action', 'Crime', 'Thriller'],
    playable: true,
    comingSoon: false,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Emily Blunt', 'Benicio Del Toro', 'Josh Brolin'],
    director: 'Denis Villeneuve',
    tagline: 'Edge-of-your-seat tension',
    createdAt: '2026-01-05T12:00:00.000Z',
  }),
  sec('Playable now', {
    movieId: 79132,
    slug: 'inception',
    assetKey: 'inception-2010',
    displayTitle: 'Inception',
    year: 2010,
    runtimeMinutes: 148,
    maturity: 'PG-13',
    tmdbVoteAverage: 8.8,
    overview:
      'A thief who enters dreams to steal secrets is offered a chance at freedom if he can plant an idea deep in a mark\'s subconscious.',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    playable: true,
    comingSoon: false,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    tagline: 'Mind-bending modern classic',
    createdAt: '2026-01-08T12:00:00.000Z',
  }),
  sec('Playable now', {
    movieId: 58559,
    slug: 'the-dark-knight',
    assetKey: 'the-dark-knight-2008',
    displayTitle: 'The Dark Knight',
    year: 2008,
    runtimeMinutes: 152,
    maturity: 'PG-13',
    tmdbVoteAverage: 9.0,
    overview:
      'Batman faces the Joker, an agent of chaos whose games force impossible moral choices on Gotham.',
    genres: ['Action', 'Crime', 'Drama'],
    playable: true,
    comingSoon: false,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    tagline: 'The standard for comic-book cinema',
    createdAt: '2026-01-10T12:00:00.000Z',
  }),
  sec('Playable now', {
    movieId: 74458,
    slug: 'shutter-island',
    assetKey: 'shutter-island-2010',
    displayTitle: 'Shutter Island',
    year: 2010,
    runtimeMinutes: 138,
    maturity: 'R',
    tmdbVoteAverage: 8.2,
    overview:
      'Two U.S. marshals investigate a disappearance at an asylum on a remote island — and sanity frays.',
    genres: ['Mystery', 'Thriller', 'Drama'],
    playable: true,
    comingSoon: false,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley'],
    director: 'Martin Scorsese',
    tagline: 'Paranoia you can’t shake',
    createdAt: '2026-01-12T12:00:00.000Z',
  }),
  // ── Kenyan & East African originals / priority ─────────────────
  sec('Kenyan originals', {
    movieId: 91000101,
    slug: 'rafiki',
    assetKey: 'rafiki-2018',
    displayTitle: 'Rafiki',
    year: 2018,
    runtimeMinutes: 82,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.2,
    overview: 'Two Kenyan women navigate family expectations and taboo in a vibrant Nairobi romance.',
    genres: ['Drama', 'Romance'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Samantha Mugatsia', 'Sheila Munyiva'],
    director: 'Wanuri Kahiu',
    filmmakerProfileSlug: 'wanuri-kahiu',
    createdAt: '2026-03-01T12:00:00.000Z',
  }),
  sec('Kenyan originals', {
    movieId: 91000102,
    slug: 'nairobi-half-life',
    assetKey: 'nairobi-half-life-2012',
    displayTitle: 'Nairobi Half Life',
    year: 2012,
    runtimeMinutes: 96,
    maturity: 'R',
    tmdbVoteAverage: 7.4,
    overview: 'A country boy arrives in Nairobi chasing acting dreams and is pulled into crime and survival.',
    genres: ['Drama', 'Crime'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Joseph Wairimu', 'Olwenya Maina'],
    director: 'David Tosh Gitonga',
    filmmakerProfileSlug: 'david-tosh-gitonga',
    createdAt: '2026-03-08T12:00:00.000Z',
  }),
  sec('Kenyan originals', {
    movieId: 91000103,
    slug: 'supa-modo',
    assetKey: 'supa-modo-2018',
    displayTitle: 'Supa Modo',
    year: 2018,
    runtimeMinutes: 74,
    maturity: 'PG',
    tmdbVoteAverage: 7.4,
    overview: 'A village unites to grant a terminally ill girl her superhero dreams.',
    genres: ['Drama', 'Family'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Stycie Waweru', 'Marrianne Nungo'],
    director: 'Likarion Wainaina',
    filmmakerProfileSlug: 'likarion-wainaina',
    createdAt: '2026-03-12T12:00:00.000Z',
  }),
  sec('Kenyan originals', {
    movieId: 91000104,
    slug: 'soul-boy',
    assetKey: 'soul-boy-2010',
    displayTitle: 'Soul Boy',
    year: 2010,
    runtimeMinutes: 61,
    maturity: 'PG',
    tmdbVoteAverage: 6.9,
    overview: 'A boy races across Nairobi on a mystical errand to save his father\'s spirit.',
    genres: ['Drama', 'Adventure'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Samson Odhiambo', 'Leila Dayan Opou'],
    director: 'Hawa Essuman',
    createdAt: '2026-03-15T12:00:00.000Z',
  }),
  sec('Kenyan originals', {
    movieId: 91000105,
    slug: 'the-first-grader',
    assetKey: 'the-first-grader-2010',
    displayTitle: 'The First Grader',
    year: 2010,
    runtimeMinutes: 103,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.4,
    overview: 'An elderly Kenyan man fights for the education denied him under colonial rule.',
    genres: ['Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Naomie Harris', 'Oliver Litondo'],
    director: 'Justin Chadwick',
    createdAt: '2026-03-18T12:00:00.000Z',
  }),
  sec('Kenyan originals', {
    movieId: 91000106,
    slug: 'disconnect-2018',
    assetKey: 'disconnect-2018',
    displayTitle: 'Disconnect',
    year: 2018,
    runtimeMinutes: 144,
    maturity: 'R',
    tmdbVoteAverage: 6.8,
    overview: 'Interwoven Nairobi stories trace desire, ethics, and technology in contemporary Kenya.',
    genres: ['Drama', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Nicholas Mutuma', 'Patricia Kihoro'],
    director: 'David Osinyo',
    createdAt: '2026-03-22T12:00:00.000Z',
  }),
  // ── Pan-African & Nollywood ────────────────────────────────────
  sec('Pan-African cinema', {
    movieId: 91000201,
    slug: 'king-of-boys',
    assetKey: 'king-of-boys-2018',
    displayTitle: 'King of Boys',
    year: 2018,
    runtimeMinutes: 182,
    maturity: 'R',
    tmdbVoteAverage: 6.5,
    overview: 'A businesswoman\'s empire in Lagos draws enemies from politics and the underworld.',
    genres: ['Crime', 'Drama', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Sola Sobowale', 'Adesua Etomi-Wellington'],
    director: 'Kemi Adetiba',
    createdAt: '2026-02-01T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000202,
    slug: 'the-wedding-party',
    assetKey: 'the-wedding-party-2016',
    displayTitle: 'The Wedding Party',
    year: 2016,
    runtimeMinutes: 110,
    maturity: 'PG-13',
    tmdbVoteAverage: 6.7,
    overview: 'Chaos erupts when two elite Lagos families collide on wedding day.',
    genres: ['Comedy', 'Romance'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Adesua Etomi', 'Banky Wellington'],
    director: 'Kemi Adetiba',
    createdAt: '2026-02-05T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000203,
    slug: 'lionheart-2018',
    assetKey: 'lionheart-2018',
    displayTitle: 'Lionheart',
    year: 2018,
    runtimeMinutes: 95,
    maturity: 'PG-13',
    tmdbVoteAverage: 6.4,
    overview: 'A woman steps up to lead her father\'s transport business in male-dominated Enugu.',
    genres: ['Drama', 'Comedy'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Genevieve Nnaji', 'Nkem Owoh'],
    director: 'Genevieve Nnaji',
    createdAt: '2026-02-10T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000204,
    slug: 'tsotsi',
    assetKey: 'tsotsi-2005',
    displayTitle: 'Tsotsi',
    year: 2005,
    runtimeMinutes: 94,
    maturity: 'R',
    tmdbVoteAverage: 7.6,
    overview: 'A Johannesburg gang leader\'s life cracks open when he steals a car and finds a baby in the back seat.',
    genres: ['Crime', 'Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Presley Chweneyagae', 'Terry Pheto'],
    director: 'Gavin Hood',
    createdAt: '2026-02-14T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000205,
    slug: 'hotel-rwanda',
    assetKey: 'hotel-rwanda-2004',
    displayTitle: 'Hotel Rwanda',
    year: 2004,
    runtimeMinutes: 121,
    maturity: 'PG-13',
    tmdbVoteAverage: 8.1,
    overview: 'A hotel manager shelters refugees during the 1994 genocide.',
    genres: ['Drama', 'History'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Don Cheadle', 'Sophie Okonedo'],
    director: 'Terry George',
    createdAt: '2026-02-18T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000206,
    slug: 'queen-of-katwe',
    assetKey: 'queen-of-katwe-2016',
    displayTitle: 'Queen of Katwe',
    year: 2016,
    runtimeMinutes: 124,
    maturity: 'PG',
    tmdbVoteAverage: 7.4,
    overview: 'A Ugandan girl discovers chess as a path out of the Katwe slum.',
    genres: ['Drama', 'Biography'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Madina Nalwanga', 'David Oyelowo', 'Lupita Nyong\'o'],
    director: 'Mira Nair',
    createdAt: '2026-02-20T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000207,
    slug: 'eyimofe',
    assetKey: 'eyimofe-2020',
    displayTitle: 'Eyimofe',
    year: 2020,
    runtimeMinutes: 115,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.0,
    overview: 'Parallel Lagos stories follow two strivers chasing visas to Europe.',
    genres: ['Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Jude Akwudike', 'Temi Badaru'],
    director: 'Arie Esiri',
    createdAt: '2026-02-22T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000208,
    slug: 'vuta-nkuvute',
    assetKey: 'vuta-nkuvute-2020',
    displayTitle: 'Vuta Nkuvute (Tug of War)',
    year: 2020,
    runtimeMinutes: 92,
    maturity: 'PG-13',
    tmdbVoteAverage: 6.8,
    overview: 'In 1950s Zanzibar, a young revolutionary shelters a runaway Indian-Zanzibari bride.',
    genres: ['Drama', 'Romance'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Ikhlas Gaffar', 'Siti Amina'],
    director: 'Amil Shivji',
    createdAt: '2026-02-24T12:00:00.000Z',
  }),
  // ── International — awards, mind-benders, tension ───────────
  sec('International acclaimed', {
    movieId: 91000301,
    slug: 'parasite-2019',
    assetKey: 'parasite-2019',
    displayTitle: 'Parasite',
    year: 2019,
    runtimeMinutes: 132,
    maturity: 'R',
    tmdbVoteAverage: 8.5,
    overview: 'Class tension ignites when one household infiltrates another — upstairs and downstairs collide.',
    genres: ['Thriller', 'Drama', 'Comedy'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Song Kang-ho', 'Choi Woo-shik', 'Park So-dam'],
    director: 'Bong Joon-ho',
    createdAt: '2026-04-01T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000302,
    slug: 'interstellar-2014',
    assetKey: 'interstellar-2014',
    displayTitle: 'Interstellar',
    year: 2014,
    runtimeMinutes: 169,
    maturity: 'PG-13',
    tmdbVoteAverage: 8.7,
    overview: 'Explorers cross a wormhole to find humanity a new home among the stars.',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: false,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    createdAt: '2026-04-03T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000303,
    slug: 'dune-2021',
    assetKey: 'dune-2021',
    displayTitle: 'Dune',
    year: 2021,
    runtimeMinutes: 155,
    maturity: 'PG-13',
    tmdbVoteAverage: 8.0,
    overview: 'Paul Atreides leads a desert people on a spice world that reshapes galactic power.',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: false,
    cast: ['Timothee Chalamet', 'Zendaya', 'Oscar Isaac'],
    director: 'Denis Villeneuve',
    createdAt: '2026-04-05T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000304,
    slug: 'blade-runner-2049',
    assetKey: 'blade-runner-2049',
    displayTitle: 'Blade Runner 2049',
    year: 2017,
    runtimeMinutes: 164,
    maturity: 'R',
    tmdbVoteAverage: 8.0,
    overview: 'A replicant-hunting LAPD officer uncovers a secret that rattles what is real.',
    genres: ['Sci-Fi', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Ryan Gosling', 'Harrison Ford'],
    director: 'Denis Villeneuve',
    createdAt: '2026-04-08T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000305,
    slug: 'arrival-2016',
    assetKey: 'arrival-2016',
    displayTitle: 'Arrival',
    year: 2016,
    runtimeMinutes: 116,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.9,
    overview: 'A linguist races to communicate with visitors whose language changes how we think about time.',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: false,
    cast: ['Amy Adams', 'Jeremy Renner'],
    director: 'Denis Villeneuve',
    createdAt: '2026-04-10T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000306,
    slug: 'prisoners-2013',
    assetKey: 'prisoners-2013',
    displayTitle: 'Prisoners',
    year: 2013,
    runtimeMinutes: 153,
    maturity: 'R',
    tmdbVoteAverage: 8.1,
    overview: 'When two girls vanish, a father pushes past the law while a detective chases unbearable leads.',
    genres: ['Crime', 'Drama', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Hugh Jackman', 'Jake Gyllenhaal'],
    director: 'Denis Villeneuve',
    createdAt: '2026-04-12T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000307,
    slug: 'whiplash-2014',
    assetKey: 'whiplash-2014',
    displayTitle: 'Whiplash',
    year: 2014,
    runtimeMinutes: 107,
    maturity: 'R',
    tmdbVoteAverage: 8.5,
    overview: 'A young drummer meets a conservatory instructor whose methods shred every boundary.',
    genres: ['Drama', 'Music'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Miles Teller', 'J.K. Simmons'],
    director: 'Damien Chazelle',
    createdAt: '2026-04-14T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000308,
    slug: 'gone-girl-2014',
    assetKey: 'gone-girl-2014',
    displayTitle: 'Gone Girl',
    year: 2014,
    runtimeMinutes: 149,
    maturity: 'R',
    tmdbVoteAverage: 8.1,
    overview: 'When a wife vanishes, media scrutiny turns her husband into the story.',
    genres: ['Thriller', 'Drama', 'Mystery'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Ben Affleck', 'Rosamund Pike'],
    director: 'David Fincher',
    createdAt: '2026-04-16T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000309,
    slug: 'memento-2000',
    assetKey: 'memento-2000',
    displayTitle: 'Memento',
    year: 2000,
    runtimeMinutes: 113,
    maturity: 'R',
    tmdbVoteAverage: 8.4,
    overview: 'A man with short-term memory loss hunts his wife\'s killer using notes and tattoos.',
    genres: ['Mystery', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Guy Pearce', 'Carrie-Anne Moss'],
    director: 'Christopher Nolan',
    createdAt: '2026-04-18T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000310,
    slug: 'oldboy-2003',
    assetKey: 'oldboy-2003',
    displayTitle: 'Oldboy',
    year: 2003,
    runtimeMinutes: 120,
    maturity: 'R',
    tmdbVoteAverage: 8.3,
    overview: 'After years of captivity, a man is freed and given days to learn why.',
    genres: ['Action', 'Thriller', 'Mystery'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Choi Min-sik', 'Yoo Ji-tae'],
    director: 'Park Chan-wook',
    createdAt: '2026-04-20T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000311,
    slug: 'moonlight-2016',
    assetKey: 'moonlight-2016',
    displayTitle: 'Moonlight',
    year: 2016,
    runtimeMinutes: 111,
    maturity: 'R',
    tmdbVoteAverage: 7.4,
    overview: 'Three chapters follow a boy becoming a man in Miami, tenderness set against hard circumstance.',
    genres: ['Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: true,
    cast: ['Mahershala Ali', 'Naomie Harris'],
    director: 'Barry Jenkins',
    createdAt: '2026-04-22T12:00:00.000Z',
  }),
  sec('International acclaimed', {
    movieId: 91000312,
    slug: 'everything-everywhere-2022',
    assetKey: 'everything-everywhere-all-at-once-2022',
    displayTitle: 'Everything Everywhere All at Once',
    year: 2022,
    runtimeMinutes: 139,
    maturity: 'R',
    tmdbVoteAverage: 7.8,
    overview: 'An IRS audit spirals into a multiverse battle for a fractured family.',
    genres: ['Sci-Fi', 'Action', 'Comedy'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: false,
    darkPsychological: false,
    cast: ['Michelle Yeoh', 'Ke Huy Quan'],
    director: 'Daniel Kwan',
    createdAt: '2026-04-24T12:00:00.000Z',
  }),
  // ── BirgenAI forward slate (placeholders — investor narrative) ─
  sec('Coming on BirgenAI', {
    movieId: 91000404,
    slug: 'Sincerely Daisy',
    assetKey: 'sincerely-daisy-2020',
    displayTitle: 'Sincerely Daisy',
    year: 2020,
    runtimeMinutes: 100,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.5,
    overview: 'A young woman from Nairobi struggles to find her place in the world after a traumatic event.',
    genres: ['Thriller', 'Drama'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Ella Maina', 'Brian Abajah', 'Sam Psenjen'],
    director: 'Nick Mutuma',
    createdAt: '2026-05-10T12:00:00.000Z',
  }),
  sec('Coming on BirgenAI', {
    movieId: 91000403,
    slug: 'nairobyy',
    assetKey: 'nairobyy-2026',
    displayTitle: 'Nairobyy',
    year: 2026,
    runtimeMinutes: 112,
    maturity: 'PG-13',
    tmdbVoteAverage: 0,
    overview: 'A crime thriller reminiscent of classic movies such as Quentin Tarantino’s Reservoir Dogs',
    genres: ['Thriller', 'Mystery'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: false,
    darkPsychological: true,
    cast: ['TBA'],
    director: 'TBA',
    createdAt: '2026-05-06T12:00:00.000Z',
  }),
  sec('Coming on BirgenAI', {
    movieId: 91000402,
    slug: 'subira',
    assetKey: 'subira-2026',
    displayTitle: 'Subira',
    year: 2026,
    runtimeMinutes: 104,
    maturity: 'R',
    tmdbVoteAverage: 0,
    overview: 'Subira, a young, free-spirited girl from the rural areas of Kenya but has traditional submissive expectations preventing her from leading the life she desires.',
    genres: ['Drama', 'Romance'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Brenda Wairimu', 'Tirath Padam', 'Nice Githinji'],
    director: 'Ravneet Sippy Chadha',
    createdAt: '2026-05-03T12:00:00.000Z',
  }),

  sec('Coming on BirgenAI', {
    movieId: 91000401,
    slug: 'lusala',
    assetKey: 'lusala-2019',
    displayTitle: 'Lusala',
    year: 2019,
    runtimeMinutes: 98,
    maturity: 'PG-13',
    tmdbVoteAverage: 0,
    overview: 'Lusala, adopted by an affluent Nairobi family a decade ago is imposed on to leave home and start on his own.',
    genres: ['Drama', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: true,
    panAfrican: false,
    darkPsychological: true,
    cast: ['TBA'],
    director: 'TBA — Kenyan creative collective',
    createdAt: '2026-05-01T12:00:00.000Z',
  }),
  sec('Coming on BirgenAI', {
    movieId: 91000405,
    slug: 'Uradi',
    assetKey: 'uradi-2021',
    displayTitle: 'Uradi',
    year: 2021,
    runtimeMinutes: 120,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.5,
    overview: 'A university student looks for a way to make quick and easy money and finds out that its not as easy as he imagined.',
    genres: ['Drama', 'Thriller'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Ensemble'],
    director: 'Various',
    createdAt: '2026-05-15T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000210,
    slug: 'sarafina',
    assetKey: 'sarafina-1992',
    displayTitle: 'Sarafina!',
    year: 1992,
    runtimeMinutes: 117,
    maturity: 'PG-13',
    tmdbVoteAverage: 7.6,
    overview: 'During apartheid, students in Soweto find voice through music and protest.',
    genres: ['Drama', 'Music'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: false,
    cast: ['Leleti Khumalo', 'Whoopi Goldberg'],
    director: 'Darrell Roodt',
    createdAt: '2026-02-26T12:00:00.000Z',
  }),
  sec('Pan-African cinema', {
    movieId: 91000209,
    slug: 'blood-diamond',
    assetKey: 'blood-diamond-2006',
    displayTitle: 'Blood Diamond',
    year: 2006,
    runtimeMinutes: 143,
    maturity: 'R',
    tmdbVoteAverage: 8.0,
    overview: 'A fisherman and a smuggler clash over a pink diamond amid civil war in Sierra Leone.',
    genres: ['Drama', 'Thriller', 'Adventure'],
    playable: false,
    comingSoon: true,
    kenyanOriginal: false,
    panAfrican: true,
    darkPsychological: true,
    cast: ['Leonardo DiCaprio', 'Djimon Hounsou', 'Jennifer Connelly'],
    director: 'Edward Zwick',
    createdAt: '2026-02-28T12:00:00.000Z',
  }),
];